#!/bin/bash

# Encontrar e matar o processo djumbai-send
pid_send=$(pgrep -f "/var/DJUMBAI/bin/djumbai-send")
if [ -n "$pid_send" ]; then
    echo "Killing process djumbai-send..."
    kill $pid_send
else
    echo "Process djumbai-send is not running."
fi

# Encontrar e matar o processo djumbai-clean
pid_clean=$(pgrep -f "/var/DJUMBAI/bin/djumbai-clean")
if [ -n "$pid_clean" ]; then
    echo "Killing process djumbai-clean..."
    kill $pid_clean
else
    echo "Process djumbai-clean is not running."
fi

# Encontrar e matar o processo djumbai-lspawn
pid_lspawn=$(pgrep -f "/var/DJUMBAI/bin/djumbai-lspawn")
if [ -n "$pid_lspawn" ]; then
    echo "Killing process djumbai-lspawn..."
    kill $pid_lspawn
else
    echo "Process djumbai-lspawn is not running."
fi


rm /tmp/clean_pipe0 > /dev/null 2>&1
rm /tmp/clean_pipe1 > /dev/null 2>&1
rm /tmp/spawn_pipe0 > /dev/null 2>&1
rm /tmp/spawn_pipe1 > /dev/null 2>&1

echo "DJUMABI terminated"
