#!/bin/bash

# Encontrar e matar o processo djumbai-send
pid_send=$(pgrep -f "/var/DJUMBAI/bin/djumbai-send")
if [ -n "$pid_send" ]; then
    echo "Matando processo djumbai-send (PID: $pid_send)..."
    kill $pid_send
else
    echo "Processo djumbai-send não está em execução."
fi

# Encontrar e matar o processo djumbai-clean
pid_clean=$(pgrep -f "/var/DJUMBAI/bin/djumbai-clean")
if [ -n "$pid_clean" ]; then
    echo "Matando processo djumbai-clean (PID: $pid_clean)..."
    kill $pid_clean
else
    echo "Processo djumbai-clean não está em execução."
fi

# Encontrar e matar o processo djumbai-lspawn
pid_lspawn=$(pgrep -f "/var/DJUMBAI/bin/djumbai-lspawn")
if [ -n "$pid_lspawn" ]; then
    echo "Matando processo djumbai-lspawn (PID: $pid_lspawn)..."
    kill $pid_lspawn
else
    echo "Processo djumbai-lspawn não está em execução."
fi

# Encontrar e matar o processo djumbai-lspawn
pid_start=$(pgrep -f "/var/DJUMBAI/bin/djumbai-start")
if [ -n "$pid_start" ]; then
    echo "Matando processo djumbai-lspawn (PID: $pid_start)..."
    kill $pid_start
else
    echo "Processo djumbai-lspawn não está em execução."
fi
